project_name: feserve
dist: bin
before:
  hooks:
    - go mod tidy
builds:

  - binary: feserve
    ldflags:
      - -s -w -X github.com/ryanbekhen/feserve.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

dockers:
- image_templates: 
  - "ghcr.io/ryanbekhen/feserve:{{ .Version }}"
  - "ghcr.io/ryanbekhen/feserve:latest"
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/ryanbekhen/feserve
  - --label=org.opencontainers.image.source=https://github.com/ryanbekhen/feserve
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

release:
  draft: true

archives:
  - rlcp: true
    format: zip
    files:
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'