project_name: feserve
dist: bin
before:
  hooks:
    - go mod tidy
builds:

  - binary: feserve
    ldflags:
      - -s -w -X github.com/ryanbekhen/feserve.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - rlcp: true
    format: zip
    files:
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'